routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'EmpresasController@index')->name('home');

Route::get('/home', 'EmpresasController@index')->name('home');

Auth::routes();

Route::get('/empresas', 'EmpresasController@index')->name('home');

//rutas de empresas:
Route::resource('empresas', 'EmpresasController');

//ruta para buscador autocomplete:
Route::get('/search', 'EmpresasController@search')->name('empresas.search');
//ruta para buscador BUSCAR(submit):
Route::get('empresas/provincias/{provincia?}/{provinciaId?}/{letras?}', 'EmpresasController@provincias')->name('empresas.provincias.index');

//rutas para los comentarios:
Route::post('/comentarios', 'RequestController@comentarios');
Route::post('/guardarComentarios', 'RequestController@guardarComentarios');

//rutas para las respuestas:
Route::post('/guardarRespuestas', 'RequestController@guardarRespuestas');

//rutas para los likes de comentarios:
Route::post('/guardarLikeComentario', 'RequestController@guardarLikeComentario');
Route::post('/guardarDislikeComentario', 'RequestController@guardarDislikeComentario');

//rutas para actos:
Route::post('/actos', 'RequestController@actos');

//rutas para los bormes:
Route::post('/bormes', 'RequestController@bormes');
//rutas para el socialite:
Route::get('redirect/{driver}', 'Auth\LoginController@redirectToProvider')
    ->name('login.provider')
    ->where('driver', implode('|', config('auth.socialite.drivers')));

Route::get('{driver}/callback', 'Auth\LoginController@handleProviderCallback')
    ->name('login.callback')
    ->where('driver', implode('|', config('auth.socialite.drivers')));

//rutas para los empleadores:
Route::get('/oferta/{empresa?}', function ($empresa = "") {
    return view('empleadores.index', compact('empresa'));
});
Route::get('/formulario/{empresa?}', function ($empresa = "") {
    return view('empleadores.formulario',compact('empresa'));
});

Route::get('/valorar/{empresa?}', function ($empresa = "") {
    return view('empresas.valorar',compact('empresa'));
});

Route::post('/valorar/guardarValoracion', 'ValoracionesController@store');

app/Empresa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use willvincent\Rateable\Rateable;

class Empresa extends Model
{
    use Rateable;
    public function bormes()
    {
        return $this->belongsToMany('App\Borme');
    }

    public function actos()
    {
        return $this->hasMany('App\Acto');
    }

    public function users()
    {
        return $this->belongsToMany('App\User')->withPivot('propietario', 'valoracion', 'equilibrio', 'beneficios', 'estabilidad', 'gestion', 'cultura');
    }

    public function comentarios()
    {
        return $this->hasMany('App\Comentario');
    }

    public function provincias()
    {
        return $this->belongsToMany('App\Provincia');
    }

    public function getRouteKeyName()
    {
        return 'empresa';
    }
}

app/Http/Controllers/EmpresasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Image;
use Illuminate\Support\Facades\File;

class EmpresasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $empresas = \App\Empresa::has('comentarios')
            ->simplePaginate(9);
        $provincias = \App\Provincia::all();
        return view('empresas.index', compact('empresas', 'provincias'));
    }

    /**
     * muestra empresas por provincias con o sin texto o provincia
     *
     * @param string $provincia
     * @param int $provinciaId
     * @param string $letras
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function provincias ($provincia = "", $provinciaId = 0, $letras = "") {

        //provincias para el buscador:
        $provincias = \App\Provincia::all();

        //en caso de que el usuario ha elegido la provincia:
        if ($provinciaId != 0) {
            $provincia = \App\Provincia::find($provinciaId);

            //en caso de que usuario ha enviado letras desde el buscador:
            if (strlen($letras) != 0) {
                //elegimos todas las empresas que contienen
                //combinación de estas letras de esta provincia:
                $empresas = $provincia->empresas()
                    ->where('empresa', 'LIKE', '%'.$letras.'%')
                    ->simplePaginate(9);
                return view('empresas.provincias.index',
                    compact('provincia', 'letras', 'empresas', 'provincias'));
             }
             //en caso de que el usuario NO ha eligido las letras:
            else {
                $empresas = $provincia->empresas()->simplePaginate(9);
                return view('empresas.provincias.index',
                    compact('provincia', 'letras', 'empresas', 'provincias'));
            }
        }
        else if ($provinciaId == 0) {
            $provincia = new \App\Provincia();
            $provincia->provincia = "todas las provincias";
            //elegimos todas las empresas que contienen
            //combinación de estas letras:
            $empresas = \App\Empresa::
                where('empresa', 'LIKE', '%'.$letras.'%')
                ->simplePaginate(9);
            return view('empresas.provincias.index',
                compact('provincia', 'letras', 'empresas', 'provincias'));
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($empresa)
    {
        $empresa = \App\Empresa::where('empresa', '=', $empresa)->first();
        try {
            $provincia = $empresa->provincias()->first();
        }
        catch (\Exception $e) {
            $provincia = new \App\Provincia();
            $provincia->provincia = "error en el link";
        }
        return view('empresas.show', compact('empresa', 'provincia'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        //autorizamos acceso SOLO a los PROPIETARIOS
        $request->user()->authorizeRoles(['propietario']);

        $empresa = \App\Empresa::find($id);

        //comprobamos si es propietario de dicha empresa
        if ($request->user()->propietarioEmpresas()->id == $id) {
            return view('empresas.edit',
                compact('empresa'));
        }

        else {
            abort(401, 'Usted no es el propietario de la empresa');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //autorizamos acceso SOLO a los PROPIETARIOS
        $request->user()->authorizeRoles(['propietario']);

        $empresa =  \App\Empresa::find($id);

        //Imagen
        $ruta = public_path().'/images/';
        if ($request->file('foto') !== null) {

            $imagenNombre = $empresa -> foto;
            //File::delete( $ruta . $imagenNombre);

            // recogida del form
            $imagenOriginal = $request->file('foto');

            // crear instancia de imagen
            $imagen = Image::make($imagenOriginal);

            // generar un nombre aleatorio para la imagen
            $temp_name = $this->random_string() . '.' . $imagenOriginal->getClientOriginalExtension();

            // guardar imagen
            // save( [ruta], [calidad])
            $imagen->save($ruta . $temp_name, 40);

            //Declaro la variable $size la cual contiene el tamaño de la imagen ya guardada, lo divido por 1024 dos veces para que sea en MB.
            $size = $imagen->filesize() / 1024 / 1024;

            //Si el tamaño es mas grande de 0.6 MB.
            if($size > 0.6){
                //Se elimina la imagen.
                File::delete($ruta.$temp_name);

                //Redirijimos a la vista un mensaje de error.
                return redirect()->back()->with('alert', 'Su imagen pesa mas de lo permitido !');
            }

        }
        else {
            $temp_name = $empresa -> foto;
        }
        //Guardo la imagen.
        $empresa->foto = $temp_name;

        $empresa -> save();

        return redirect()->action('EmpresasController@show',$empresa->empresa);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function search(Request $request)
    {
        if (isset($request->search)) {
            if ($request->provincia == 0) {
                $empresas = \App\Empresa::select('empresa')->where('empresa', 'LIKE', '%'.$request->search.'%')->take(6)->get();
                return \response()->json($empresas);
            }
            else {
                $provincia = \App\Provincia::find($request->provincia);

                $empresas = $provincia->empresas()->select('empresa')->where('empresa', 'LIKE', '%'.$request->search.'%')->take(6)->get();
                return \response()->json($empresas);
            }
        }
    }

    protected function random_string()
    {
        $key = '';
        $keys = array_merge( range('a','z'), range(0,9) );

        for($i=0; $i<10; $i++)
        {
            $key .= $keys[array_rand($keys)];
        }

        return $key;
    }
}

resources/views/empresas/edit.blade.php
@extends('layouts/app')

@section('content')

<div class="container">
    <form id="save" method="POST" action="{{ route('empresas.update', [$empresa->id]) }}" enctype="multipart/form-data">
        {{ csrf_field() }}
        <div class="row">
            <div class="col-sm-4 mx-auto">
                <!-- Mensaje de Error llamado por el JS -->
                <div class="alert alert-danger" id="alerta" style="display: none">Su imagen pesa mas de lo permitido!</div>

                <!-- Mensaje de Error llamado por Laravel -->
                @if (session('alert'))
                    <div class="alert alert-danger">Su imagen pesa mas de lo permitido!</div>
            @endif

            <!-- Empresa -->
                <div class="card" style="width: 22rem;">
                    <input name="_method" type="hidden" value="PATCH">
                    <img id="imagen" src="@if($empresa->foto != null) {{asset('/images/'.$empresa->foto)}} @else http://www.agwestdist.com/storage/img/noimg.png @endif" class="card-img-top" alt="...">

                    <div class="button">
                        <input onchange="comprobarPeso(this)" id="img" data-input="false" type="file" data-badge="false" accept="image/x-png,image/gif,image/jpeg" name="foto" style="display:none" />
                        <a href="" id="upload_link">Cambiar Imagen</a>
                    </div>

                    <div class="card-body">

                        <h5 class="card-title">
                            <label>Empresa: </label>
                            <input required value="{{ $empresa->empresa }}" name="empresa" class="form-control">
                        </h5>
                        <label>Datos registrales : </label>
                        <textarea class="form-control" rows="3" name="datos">@if(isset($empresa->datos_registrales)){{ $empresa->datos_registrales }}@endif</textarea>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <label>nº anuncio: </label>
                            <input required value="{{ $empresa->anuncio_id}}" name="anuncio" class="form-control">
                        </li>
                        <li class="list-group-item">
                            <p>
                                Aquí irá información que se podrá cambiar, por falta de tiempo no lo hacemos ahora! Lo que funciona bien es el control de la imagen!
                            </p>
                        </li>
                    </ul>
                    <div class="card-body">

                        {{csrf_field ()}}
                        <a href="{{url('empresas',$empresa->empresa)}}" class="card-link">	&lt;- Volver</a>
                        <a href="javascript:{}" onclick="document.getElementById('save').submit();" class="card-link" style="color: green;" value = "store">Guardar</a>

                    </div>
                </div>
                <!-- Espacio -->
                <figure class="highlight">
                </figure>

            </div>
        </div>
    </form>
</div>

<script>
    $(function(){
        $("#upload_link").on('click', function(e){
            e.preventDefault();
            $("#img:hidden").trigger('click');
        });
    });

    function comprobarPeso(file) {
        var FileSize = file.files[0].size / 1024 / 1024;

        if (FileSize > 2) {
            //Si el tamaño de la imagen es mas grande que 1 MB.
            show();
            $(file).val('');
        }else{
            //Si es mas pequeño se ejecuta la funcion previewFile().
            hide();
            previewFile();
        }
    }

    function previewFile() {
        var preview = document.getElementById('imagen');
        var file    = document.querySelector('input[type=file]').files[0];
        var reader  = new FileReader();

        reader.onloadend = function () {
            preview.src = reader.result;
        }

        if (file) {
            reader.readAsDataURL(file);
        } else {
            preview.src = "";
        }
    }

    //Funcion para mostrar el mensaje de Error.
    function show(){
        var x = document.getElementById("alerta");
        x.style.display = "block";
    }

    //Funcion para esconder el mensaje de Error.
    function hide() {
        var x = document.getElementById("alerta");
        x.style.display = "none";
    }

</script>
@endsection

resources/views/empresas/index.blade.php
@extends('layouts/app')

@section('content')

        @include('empresas.partials.buscador')
        @include('empresas.partials.empresasMasComentadas')
@endsection

resources/views/empresas/show.blade.php
@extends('layouts/app')

@section('content')
    @include('empresas.partials.empresa')
@endsection

resources/views/empresas/valorar.blade.php
@extends('layouts/app')

@section('content')
    @include('empresas.partials.valorar')
@endsection